export const FIND_USER_BY_USER_NAME_HAS_ERR = 'FIND_USER_BY_USER_NAME_HAS_ERR';
export const FIND_USER_BY_USER_NAME_SUCCESS = 'FIND_USER_BY_USER_NAME_SUCCESS';
export const FIND_PRODUCTBYNAME_HAS_ERR = 'FIND_PRODUCTBYNAME_HAS_ERR';
export const FIND_PRODUCTBYNAME_SUCCESS = 'FIND_PRODUCTBYNAME_SUCCESS';
export const FIND_PRODUCTBYCATEGORY_HAS_ERR = 'FIND_PRODUCTBYCATEGORY_HAS_ERR';
export const FIND_PRODUCTBYCATEGORY_SUCCESS = 'FIND_PRODUCTBYCATEGORY_SUCCESS';
export const CREATE_PRODUCT_HAS_ERR = 'CREATE_PRODUCT_HAS_ERR';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';