export const FIND_USER_BY_USER_NAME_HAS_ERR = 'FIND_USER_BY_USER_NAME_HAS_ERR';
export const FIND_USER_BY_USER_NAME_SUCCESS = 'FIND_USER_BY_USER_NAME_SUCCESS';
export const FIND_PRODUCTBYNAME_HAS_ERR = 'FIND_PRODUCTBYNAME_HAS_ERR';
export const FIND_PRODUCTBYNAME_SUCCESS = 'FIND_PRODUCTBYNAME_SUCCESS';
export const FIND_PRODUCTBYCATEGORY = 'FIND_PRODUCTBYCATEGORY';
export const CREATE_PRODUCT_HAS_ERR = 'CREATE_PRODUCT_HAS_ERR';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const GET_CATEGORY = 'GET_CATEGORY';
